### ISSUE TITLE
Hash for cli jar@1.4.1 does not match available release

### ISSUE THREAD

**Issue by erkmos** [LoopPerfect/homebrew-lp#14]
The hash listed at https://github.com/LoopPerfect/homebrew-lp/blob/master/buckaroo%401.4.1.rb#L10

Does not match the actual hash of the published file:
```
curl -Ls https://github.com/LoopPerfect/buckaroo/releases/download/v1.4.1/buckaroo-cli.jar|shasum -a 256
025582b9b67788251a3d1fa8a72ca596a0ce09a0f782b4934bbe773b91d651ba  -
```

This causes the homebrew installation to fail with a hash checksum mismatch:

```
==> Downloading https://github.com/LoopPerfect/buckaroo/releases/download/v1.4.1/buckaroo-cli.jar
Already downloaded: /Users/erik/Library/Caches/Homebrew/downloads/cd0cb1c56dda959261b80100753eed8e92a334e62dc6e7e37ded94f9c92287f3--buckaroo-cli.jar
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: c6abf8031c59dbea9c46d99a90e051d03de33d3bee6846a865441ad5360e9b30
Actual: 025582b9b67788251a3d1fa8a72ca596a0ce09a0f782b4934bbe773b91d651ba
Archive: /Users/erik/Library/Caches/Homebrew/downloads/cd0cb1c56dda959261b80100753eed8e92a334e62dc6e7e37ded94f9c92287f3--buckaroo-cli.jar
To retry an incomplete download, remove the file above.
```

**Comment by njlr** [comment]
Thanks for the heads-up. Taking a look now...

**Comment by njlr** [comment]
The sha was indeed incorrect. I have updated it now 

```bash=
$ curl -Ls https://github.com/LoopPerfect/buckaroo/releases/download/v1.4.1/buckaroo-cli.jar | openssl sha256 
025582b9b67788251a3d1fa8a72ca596a0ce09a0f782b4934bbe773b91d651ba
```

**Comment by erkmos** [comment]
Thanks, it works now. But I am a bit curious why the hash was wrong?

**Comment by erkmos** [comment]
Anyway, will close this as the issue is fixed now. Thanks for a quick reply!

**Comment by njlr** [comment]
My theory: 

The releases are built by Travis CI and pushed back to GitHub. There was a mistake in `1.4.1` that was patched a few minutes later, so Travis updated the `.jar`. The reason I didn't notice when testing the release was that Homebrew had cached everything on my machine. 

It might be worth running a CI on this repo as well to catch such things.
