### ISSUE TITLE
Installing via linuxbrew doesn't install binary correctly

### ISSUE THREAD

**Issue by thoughton** [LoopPerfect/homebrew-lp#17]
Installing `loopperfect/lp/buckaroo@2.2.0` via `linuxbrew` (homebrew for linux) seems to complete successfully, but doesn't seem to correctly install the binary - or perhaps it fails to create a symlink to it?

Here's what gets installed:
```
~$ find .linuxbrew/Cellar/buckaroo@2.2.0
.linuxbrew/Cellar/buckaroo@2.2.0
.linuxbrew/Cellar/buckaroo@2.2.0/macos
.linuxbrew/Cellar/buckaroo@2.2.0/macos/libexec
.linuxbrew/Cellar/buckaroo@2.2.0/macos/.brew
.linuxbrew/Cellar/buckaroo@2.2.0/macos/.brew/buckaroo@2.2.0.rb
.linuxbrew/Cellar/buckaroo@2.2.0/macos/INSTALL_RECEIPT.json
.linuxbrew/Cellar/buckaroo@2.2.0/macos/bin
.linuxbrew/Cellar/buckaroo@2.2.0/macos/bin/buckaroo

~$ ls -l .linuxbrew/Cellar/buckaroo@2.2.0/macos/bin/buckaroo
-r--r--r-- 1 68576920 .linuxbrew/Cellar/buckaroo@2.2.0/macos/bin/buckaroo
```

(Obviously the `macos` directory is somewhat suspicious here, but I wasn't sure if that was just an unfortunate naming convention.)

**Comment by njlr** [comment]
Hi @thoughton :wave: 

The Homebrew package points to the macOS binary for Buckaroo. 

The recommended way to install Buckaroo on Linux is just to `wget` the exectuable: https://github.com/LoopPerfect/buckaroo/releases/tag/v2.2.0

However, perhaps we can have a Homebrew package that supports macOS and Linux. 

I will look into it.

**Comment by njlr** [comment]
OK, so I added a switch to the formula for Linux; it seems to work on my machine. 

Can you give it a try?

**Comment by thoughton** [comment]
Yep that works perfectly! Thanks for the quick response!
